
version: '3.8'

networks:
  basket_net:
    driver: bridge

volumes:
  db:
    driver: local

services:

  genropy:
    build:
      context: gestionale/
      dockerfile: Dockerfile
    command: bash -c "./start_genropy.sh"
    ports:
      - 8080:8080
    networks:
      - basket_net
    depends_on:
      - postgres 

  sito:
    build:
      context: sito/
      dockerfile: Dockerfile
    command: bash -c "python3 app.py"
    volumes:
      - ./sito:/app
    networks:
      - basket_net
    ports:
      - "5000:5000"

  postgres:
    image: postgres:11.11
    volumes:
      - db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mybasket
      - PGUSER=postgres
    ports:
      - '5432:5432'
    networks:
      - basket_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  adminer:
    image: adminer
    ports:
      - '8081:8080'
    networks:
      - basket_net
    depends_on:
      - postgres