"""Initial migration.

Revision ID: 1142a91c6277
Revises: 7d753679d7b0
Create Date: 2022-08-20 17:35:10.645717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1142a91c6277'
down_revision = '7d753679d7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iscritti', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iscritti', sa.Column('tipo', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
