"""seconda migrazione

Revision ID: 2f0f5b4865ac
Revises: 91cf533c4b70
Create Date: 2022-07-05 12:50:45.508476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f0f5b4865ac'
down_revision = '91cf533c4b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iscritti', sa.Column('identita', sa.LargeBinary(), nullable=True))
    op.add_column('iscritti', sa.Column('iscrizione', sa.LargeBinary(), nullable=True))
    op.add_column('iscritti', sa.Column('identita_caricata', sa.Boolean(), nullable=True))
    op.add_column('iscritti', sa.Column('iscrizione_caricata', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iscritti', 'iscrizione_caricata')
    op.drop_column('iscritti', 'identita_caricata')
    op.drop_column('iscritti', 'iscrizione')
    op.drop_column('iscritti', 'identita')
    # ### end Alembic commands ###
