"""Initial migration.

Revision ID: 7d753679d7b0
Revises: 2f0f5b4865ac
Create Date: 2022-08-19 20:13:50.080510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d753679d7b0'
down_revision = '2f0f5b4865ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iscritti', sa.Column('nome', sa.String(length=150), nullable=True))
    op.add_column('iscritti', sa.Column('cognome', sa.String(length=150), nullable=True))
    op.drop_column('iscritti', 'first_name')
    op.drop_column('iscritti', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iscritti', sa.Column('surname', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('iscritti', sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('iscritti', 'cognome')
    op.drop_column('iscritti', 'nome')
    # ### end Alembic commands ###
