"""Initial migration.

Revision ID: 905760cea27a
Revises: 1142a91c6277
Create Date: 2022-08-20 18:16:27.153025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905760cea27a'
down_revision = '1142a91c6277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iscritti', sa.Column('luogo_di_nascita', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iscritti', 'luogo_di_nascita')
    # ### end Alembic commands ###
